services:
  thunders-api:
    image: thunders/thunders-api:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5002    
      - ConnectionStrings__DefaultConnection=Host=db;Database=thunders-tasks-db;Username=postgres;Password=thunders@123
    networks:
      - app-thunders
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thunders@123
      POSTGRES_DB: thunders-tasks-db
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-thunders

volumes:
  pgdata:

networks:
  app-thunders:
    driver: bridge